### ISSUE TITLE
image won't build

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-example-notebooks#26]
This is what I get on the latest image of this repo

```
Fetching package metadata .................
Solving package specifications:
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /srv/conda  (writable)
    default environment : /srv/conda
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /srv/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.4 Linux/4.4.111+ debian/stretch/sid glibc/2.26
                UID:GID : 1000:1000

`$ /srv/conda/bin/conda-env update -v -n root -f binder/environment.yml`




    Traceback (most recent call last):
      File "/srv/conda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/srv/conda/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 106, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/srv/conda/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 489, in install_actions_list
        for specs_by_prefix in required_solves]
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 489, in <listcomp>
        for specs_by_prefix in required_solves]
      File "/srv/conda/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/srv/conda/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "/srv/conda/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
        reduced_index = self.get_reduced_index(specs)
      File "/srv/conda/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
        specs, features = self.verify_specs(specs)
      File "/srv/conda/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
        raise ResolvePackageNotFound(bad_deps)
    conda.exceptions.ResolvePackageNotFound:
      - dask-kubernetes
      - python-kubernetes 4

Removing intermediate container 34826b18a83f
The command '/bin/sh -c conda env update -v -n root -f "binder/environment.yml" && conda clean -tipsy' returned a non-zero code: 1
```

**Comment by jhamman** [comment]
This should be fixed as of https://github.com/pangeo-data/pangeo-binder/commit/010a6e628e5774a0cbb400bde88abd9c07ae761c. @rabernat - can you roll back the change to the readme.
